config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/ask', to: 'questions#ask'
  get '/answer', to: 'questions#answer'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def ask
  end
  def answer
    @questions = params[:questions]
    if @questions == "I am going to work"
      @answer = "Great!"
    elsif @questions.ends_with?("?")
      @answer = "Silly question. Get dressed and go to work!"
    else 
      @answer = "I don't care. Get dressed and go to work!"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/answer.html.erb
Hello
  <%= @answer %>
  <a href="/ask">Vuelve a preguntar</a>
  <%= link_to "Vuelve a preguntar", ask_path %>

app/views/questions/ask.html.erb
<form action="/answer">
  <input type="text" name="questions">
  <input type="submit" value="Any questions? Ask here!">
</form>